[{:title "Announcing Sauerbraten Day of Sobriety, a New Tournament"
  :author "mefisto"
  :date (tc/to-date (date-time 2013 9 17 20 30))
  :category "home"
  :content "
Feeling down because there's no Sauerbraten tournament for you to play
in? Singing the blues because a certain other event that shared the same
initials as our tournament put a stop to Sauerbraten tournament fun?

Well dry your tears because there's a new tournament in town! Prepare for
a day of very serious Sauerbraten competition. Prepare for... a
**Day of Sobriety**.

![Day of Sobriety Drunken Sadness](/img/coming-soon.jpg)

## Coming Soon!

We are still putting together all the plans and schemes and empty liquor
bottles (well, they're still full for now)... but for now we want to know
who is interested in playing. If you could please
**sign up with your email address in that form over to the left**
we will be able to keep in touch with updates!

### So just who are you people?

This tournament is being run by echo-echo, mefisto, misc with awesome special
assistance from notas, bbk, and others! (Special thanks to bbk for the great
logos and images)

### Why are you doing this? WHY?

Everyone involved in the Sauerbraten DoS (the Day of Sobriety DoS, not the
other one with those other people that we will not speak of anymore until
the next chance to bring it up) believes that Sauerbraten needs some good
competition! We've all been around this community for years, and we sincerely
want everyone to have a good time and see Sauerbraten succeed.

### Why should we trust you guys, huh, huh?

We want to address your concerns. Please ask echo-echo any questions and he
will be able to make you feel better. Also, he is an engineer, he knows about
electric circuits, and you have delicate body parts. Just saying.

### When is this damn thing gonna be?

Soon, ok? We got a few things to line up, gotta talk to some people, got some
splines to reticulate, you know?

Seriously, we hope to have an announcement of the time of the first event real
soon now.

### Do you need some help, eh? How can I contact you?

Yes! If you want to help out, you can:
* Send an email to mefisto. The address is his nick at sauerworld.org
* Come see us on IRC. The channel #sdos on the Gamesurge network

### Did I hear that there might be cash prizes???

As a matter of fact, we are currently discussing the possibility of offering
cash prizes for winners. Stay tuned!"}
 {:title "Updates: Format, Poll, Refs Needed"
  :author "mefisto"
  :date (tc/to-date (date-time 2013 9 20 22 30))
  :category "home"
  :content "
While we work on getting all the details together, there are a few things we
can reveal in the meantime!

## Tournament Format

The format for the Day of Sobriety Tournament is going to be double-elimination,
using an initial all-vs-all game to determine the seed rankings.

What does this mean?

First, it means that in addition to the all-vs-all game, everyone who enters the
tourney will be able to play at least 2 real games.

Second, it means that it can be organized in a nice, standard way. We will use
the double-elimination brackets generated by [Challonge](http://challonge.com/)
to determine the games, and allow everyone playing and watching to keep
track of what is going on.

Lastly, it means that we'll have to be very time efficient to get all those
games in. In order do make this happen, we're going to do something that
hasn't been done in a Sauerbraten tournament for a long time. We will have
multiple game servers running during the tournament, and will play multiple
games at the same time.

We're really excited about being able to offer a tournament that will let
everyone participate and play.

## Game Modes Poll

We are going to play 3 modes in the first tournament. We'd like to hear from
you what modes you'd like us to feature.

In the next few days, we will send out a poll to everyone on our email list. So
if you aren't on our list yet, **sign up using the form over there on the left.**

## Help Needed

As you can imagine, it will take some manpower to run all these games, so we are
looking for volunteers to help as refs during the games. Let us know if you're
interested!"}]
